// GENERATED by `s2s build` from the plugin's gamedata — DO NOT EDIT.
// The EntityRef import is REQUIRED: a `declare module` augmentation resolves type names in its
// own file scope, so an un-imported EntityRef degrades to an error skipLibCheck can swallow.
import type { EntityRef } from "@s2script/sdk/entity";

declare module "@s2script/sdk/unsafe" {
  interface EngineCalls {
    createHeGrenade: (position: { readonly x: number; readonly y: number; readonly z: number }, angles: { readonly x: number; readonly y: number; readonly z: number }, velocity: { readonly x: number; readonly y: number; readonly z: number }, velocityAngles: { readonly x: number; readonly y: number; readonly z: number }, thrower: EntityRef | null, weaponId: number, team: number) => EntityRef | null;
  }
}
